name: run-integration-test
run-name: Run CreateInvoice integration test.
on: [push, workflow_dispatch]
jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v4
      - name: Add authentication key for Magento 2 composer repository.
        run: composer config -g http-basic.repo.magento.com $MAGENTO_PUB_KEY $MAGENTO_PRIVATE_KEY
      - name: Add Magento 2 composer repository.
        run: composer config repositories.repo.magento.com composer https://repo.magento.com
      - name: Create composer Magento 2 project.
        run: composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2
      - name: Test
        run: pwd
      - name: Test 2
        run: ls -la && ls ../

    

