name: run-phpcs
run-name: Run PHP_CodeSniffer with Magento Coding Standard.
on: workflow_dispatch
jobs:
  run-phpcs-with-magento-coding-standard:
    runs-on: ubuntu-latest
    steps:
      - run: git clone git@github.com:magento/magento-coding-standard.git
      - run: composer install -d magento-coding-standard
      - run: php magento-coding-standard/vendor/bin/phpcs --standard=Magento2 .
