name: run-phpcs
run-name: Check files using PHP_CodeSniffer with Magento Coding Standard.
on: workflow_dispatch
jobs:
  run-phpcs-with-magento-coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v4
      - name: Install Magento Coding Standard using Composer.
        run: composer create-project magento/magento-coding-standard --stability=dev magento-coding-standard
      - name: run PHP_CodeSniffer with Magento Coding Standard.
      - run: php magento-coding-standard/vendor/bin/phpcs --ignore=.github/,magento-coding-standard/ --standard=Magento2 .
