name: run-phpcs
run-name: Use PHP_CodeSniffer with Magento Coding Standard.
on: workflow_dispatch
jobs:
  install-phpcs-with-magento-coding-standard:
    runs-on: ubuntu-latest
    steps:
      - run: composer create-project magento/magento-coding-standard --stability=stable magento-coding-standard
      - run: php magento-coding-standard/vendor/bin/phpcs --standard='Magento2' .
